import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pocket_chat/src/models/message.dart';
import 'package:pocket_chat/src/models/session.dart';
import 'package:objectbox/objectbox.dart';
import 'package:pocket_chat/objectbox.g.dart'; // Generated by `flutter pub run build_runner build`

class ObjectBoxService {
  late Store store;
  late Box<Message> messageBox;
  late Box<Session> sessionBox;

  ObjectBoxService._create();

  static Future<ObjectBoxService> create() async {
    final objectbox = ObjectBoxService._create();

    // Define the directory for the database
    final dir = await getApplicationDocumentsDirectory();
    final dbDir = join(dir.path, 'chat_db');

    // Create the store
    objectbox.store = await openStore(directory: dbDir);
    objectbox.messageBox = objectbox.store.box<Message>();
    objectbox.sessionBox = objectbox.store.box<Session>();

    return objectbox;
  }

  // Add a message to the database
  Future<int> addMessage(Message message) async {
    return messageBox.put(message);
  }

  // Add a session to the database
  Future<int> addSession(Session session) async {
    return sessionBox.put(session);
  }

  Future<List<Message>> getMessagesBySessionId(int sessionId) async {
    final query = messageBox
        .query(Message_.sessionId.equals(sessionId))
        .order(Message_.timestamp)
        .build();
    try {
      return query.find();
    } finally {
      query.close();
    }
  }


  Stream<List<Message>> getMessagesBySessionIdStream(int sessionId) {
    return messageBox
        .query(Message_.sessionId.equals(sessionId))
        .order(Message_.timestamp)
        .watch(triggerImmediately: true)
        .map((query) => query.find());
  }

  // Delete all messages
  Future<void> clearAllMessages() async {
    await messageBox.removeAll();
  }

  Stream<List<Session>> getAllSessionsStream() {
    return sessionBox
        .query()
        .order(Session_.timestamp, flags: Order.descending)
        .watch(triggerImmediately: true)
        .map((query) => query.find());
  }

  // Close the database
  void close() {
    store.close();
  }
}
