import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pocket_chat/src/models/message.dart';
import 'package:objectbox/objectbox.dart';
import 'package:pocket_chat/objectbox.g.dart'; // Generated by `flutter pub run build_runner build`

class ObjectBoxService {
  late Store store;
  late Box<Message> messageBox;

  ObjectBoxService._create();

  static Future<ObjectBoxService> create() async {
    final objectbox = ObjectBoxService._create();

    // Define the directory for the database
    final dir = await getApplicationDocumentsDirectory();
    final dbDir = join(dir.path, 'chat_db');

    // Create the store
    objectbox.store = await openStore(directory: dbDir);
    objectbox.messageBox = objectbox.store.box<Message>();

    return objectbox;
  }

  // Add a message to the database
  Future<int> addMessage(Message message) async {
    return messageBox.put(message);
  }

  // Get all messages from the database
  Stream<List<Message>> getAllMessagesStream() {
    return messageBox
        .query()
        .order(Message_.timestamp)
        .watch(triggerImmediately: true)
        .map((query) => query.find());
  }

  // Delete all messages
  Future<void> clearAllMessages() async {
    await messageBox.removeAll();
  }

  // Close the database
  void close() {
    store.close();
  }
}
